apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-line-gateway
  namespace: default
spec:
  gatewayClassName: eg # Change to your Gateway API implementation
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: dashboard-direct
      protocol: HTTP
      port: 8002
      allowedRoutes:
        namespaces:
          from: All
