apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.ipAddressPool.name }}
  namespace: metallb-system
spec:
  addresses:
    - {{ .Values.ipAddressPool.addressRangeStart }}-{{ .Values.ipAddressPool.addressRangeEnd }}
