{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "minio.fullname" . }}-api
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  {{- if .Values.gateway.parentRef }}
  parentRefs:
  - name: {{ .Values.gateway.parentRef.name }}
    namespace: {{ .Values.gateway.parentRef.namespace }}
  {{- end }}
  {{- if .Values.gateway.api.enabled }}
  hostnames:
  - {{ .Values.gateway.api.host | quote }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ include "minio.fullname" . }}
      port: {{ .Values.service.apiPort }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "minio.fullname" . }}-console
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  {{- if .Values.gateway.parentRef }}
  parentRefs:
  - name: {{ .Values.gateway.parentRef.name }}
    namespace: {{ .Values.gateway.parentRef.namespace }}
  {{- end }}
  {{- if .Values.gateway.console.enabled }}
  hostnames:
  - {{ .Values.gateway.console.host | quote }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ include "minio.fullname" . }}
      port: {{ .Values.service.consolePort }}
{{- end }}
