{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "minio.fullname" . }}-ingress
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
  {{- if .Values.ingress.api.enabled }}
  - host: {{ .Values.ingress.api.host | quote }}
    http:
      paths:
      - path: {{ .Values.ingress.api.path }}
        pathType: {{ .Values.ingress.api.pathType }}
        backend:
          service:
            name: {{ include "minio.fullname" . }}
            port:
              number: {{ .Values.service.apiPort }}
  {{- end }}
  {{- if .Values.ingress.console.enabled }}
  - host: {{ .Values.ingress.console.host | quote }}
    http:
      paths:
      - path: {{ .Values.ingress.console.path }}
        pathType: {{ .Values.ingress.console.pathType }}
        backend:
          service:
            name: {{ include "minio.fullname" . }}
            port:
              number: {{ .Values.service.consolePort }}
  {{- end }}
{{- end }}
