apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}-secret
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
stringData:
  rootUser: {{ .Values.auth.rootUser | quote }}
  rootPassword: {{ .Values.auth.rootPassword | quote }}
